on:
  push:
    branches: [main]
  workflow_dispatch:

name: deploy-mlflow-testing-instance

jobs:
  deploy-mlflow-testing-instance:
    runs-on: ubuntu-latest
    env:
      S3_URI: ${{ secrets.S3_URI }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy MLFlow Instance
        run: ./deploy.sh
        working-directory: inst/instance
